#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by arch/arm/Makefile
 *
 */

#define TSK_ACTIVE_MM 112 /* offsetof(struct task_struct, active_mm) */

#define TI_FLAGS 0 /* offsetof(struct thread_info, flags) */
#define TI_PREEMPT 4 /* offsetof(struct thread_info, preempt_count) */
#define TI_ADDR_LIMIT 8 /* offsetof(struct thread_info, addr_limit) */
#define TI_TASK 12 /* offsetof(struct thread_info, task) */
#define TI_EXEC_DOMAIN 16 /* offsetof(struct thread_info, exec_domain) */
#define TI_CPU 20 /* offsetof(struct thread_info, cpu) */
#define TI_CPU_DOMAIN 24 /* offsetof(struct thread_info, cpu_domain) */
#define TI_CPU_SAVE 28 /* offsetof(struct thread_info, cpu_context) */
#define TI_USED_CP 76 /* offsetof(struct thread_info, used_cp) */
#define TI_TP_VALUE 92 /* offsetof(struct thread_info, tp_value) */
#define TI_FPSTATE 96 /* offsetof(struct thread_info, fpstate) */
#define TI_VFPSTATE 240 /* offsetof(struct thread_info, vfpstate) */
#define TI_IWMMXT_STATE 96 /* (offsetof(struct thread_info, fpstate)+4)&~7 */

#define VMA_VM_MM 0 /* offsetof(struct vm_area_struct, vm_mm) */
#define VMA_VM_FLAGS 20 /* offsetof(struct vm_area_struct, vm_flags) */

#define VM_EXEC 4 /* VM_EXEC */

#define PAGE_SZ 4096 /* PAGE_SIZE */
#define VIRT_OFFSET -1073741824 /* PAGE_OFFSET */

#define SYS_ERROR0 10420224 /* 0x9f0000 */

#define SIZEOF_MACHINE_DESC 56 /* sizeof(struct machine_desc) */

#endif
