#ifndef _CSLR_IMCOP_1_H_
#define _CSLR_IMCOP_1_H_
/*********************************************************************
 * Copyright (C) 2003-2005 Texas Instruments Incorporated. 
 * All Rights Reserved 
 *********************************************************************/
 /** \file cslr_imcop_1.h
 * 
 * \brief This file contains the Register Desciptions for IMCOP
 * 
 *********************************************************************/

#include <cslr.h>

#include <tistdtypes.h>

/**************************************************************************\
* Register Overlay Structure
\**************************************************************************/
typedef struct  {
    volatile Uint16 CLKC;
    volatile Uint16 BUFSW;
    volatile Uint16 RSVD0[126];
    volatile Uint16 INTC_GEN;
    volatile Uint16 INTC_CFG;
    volatile Uint16 INTC_STAT;
    volatile Uint16 INTC_MSK;
    volatile Uint16 INTC_ARMCFG;
    volatile Uint16 INTC_SDMACFG;
    volatile Uint16 INTC_COPCCFG;
    volatile Uint16 INTC_RCNTCFG;
    volatile Uint16 INTC_DCTCFG;
    volatile Uint16 INTC_BSPCFG;
    volatile Uint16 INTC_QIQCFG;
    volatile Uint16 INTC_VLDCFG;
    volatile Uint16 INTC_BIMCFG;
    volatile Uint16 INTC_IMXCFG;
    volatile Uint16 INTC_VLCDCFG;
    volatile Uint16 INTC_DBGC;
    volatile Uint16 INTC_HWBPA;
    volatile Uint16 INTC_BPST;
    volatile Uint16 INTC_TMR;
    volatile Uint16 INTC_GENINT;
    volatile Uint16 INTC_TESTINT;
    volatile Uint16 INTC_EMU;
    volatile Uint16 RSVD1[106];
    volatile Uint16 CFG_DMA;
    volatile Uint16 CFG_RADDRL;
    volatile Uint16 CFG_RADDRH;
    volatile Uint16 CFG_WADDRL;
    volatile Uint16 CFG_WADDRH;
    volatile Uint16 CFG_RDATAL;
    volatile Uint16 CFG_RDATAH;
    volatile Uint16 CFG_WDATA;
} CSL_ImcopRegs;

/**************************************************************************\
* Field Definition Macros
\**************************************************************************/

/* CLKC */

#define CSL_IMCOP_CLKC_CLKCON_MASK       (0x0003u)
#define CSL_IMCOP_CLKC_CLKCON_SHIFT      (0x0000u)
#define CSL_IMCOP_CLKC_CLKCON_RESETVAL   (0x0000u)

/*----CLKCON Tokens----*/
#define CSL_IMCOP_CLKC_CLKCON_OFF        (0x0000u)
#define CSL_IMCOP_CLKC_CLKCON_ENABLE     (0x0002u)
#define CSL_IMCOP_CLKC_CLKCON_AUTO       (0x0003u)

#define CSL_IMCOP_CLKC_RESETVAL          (0x0000u)

/* BUFSW */

#define CSL_IMCOP_BUFSW_PMEMCON_MASK     (0x0003u)
#define CSL_IMCOP_BUFSW_PMEMCON_SHIFT    (0x0000u)
#define CSL_IMCOP_BUFSW_PMEMCON_RESETVAL (0x0000u)

/*----PMEMCON Tokens----*/
#define CSL_IMCOP_BUFSW_PMEMCON_CPDMA    (0x0000u)
#define CSL_IMCOP_BUFSW_PMEMCON_SEQUENCER (0x0001u)

#define CSL_IMCOP_BUFSW_RESETVAL         (0x0000u)

/* INTC_GEN */

#define CSL_IMCOP_INTC_GEN_SQR_ARM_MASK  (0x0002u)
#define CSL_IMCOP_INTC_GEN_SQR_ARM_SHIFT (0x0001u)
#define CSL_IMCOP_INTC_GEN_SQR_ARM_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_GEN_ARM_SQR_MASK  (0x0001u)
#define CSL_IMCOP_INTC_GEN_ARM_SQR_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_GEN_ARM_SQR_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_GEN_RESETVAL      (0x0000u)

/* INTC_CFG */

#define CSL_IMCOP_INTC_CFG_SYNC_INT_MASK (0x0002u)
#define CSL_IMCOP_INTC_CFG_SYNC_INT_SHIFT (0x0001u)
#define CSL_IMCOP_INTC_CFG_SYNC_INT_RESETVAL (0x0000u)

/*----SYNC_INT Tokens----*/
#define CSL_IMCOP_INTC_CFG_SYNC_INT_SYNC (0x0000u)
#define CSL_IMCOP_INTC_CFG_SYNC_INT_INTERRUPT (0x0001u)

#define CSL_IMCOP_INTC_CFG_SYNC_LGC_MASK (0x0001u)
#define CSL_IMCOP_INTC_CFG_SYNC_LGC_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_CFG_SYNC_LGC_RESETVAL (0x0000u)

/*----SYNC_LGC Tokens----*/
#define CSL_IMCOP_INTC_CFG_SYNC_LGC_LOGICALAND (0x0000u)
#define CSL_IMCOP_INTC_CFG_SYNC_LGC_LOGICALOR (0x0001u)

#define CSL_IMCOP_INTC_CFG_RESETVAL      (0x0000u)

/* INTC_STAT */

#define CSL_IMCOP_INTC_STAT_ARM_STAT_MASK (0x0400u)
#define CSL_IMCOP_INTC_STAT_ARM_STAT_SHIFT (0x000Au)
#define CSL_IMCOP_INTC_STAT_ARM_STAT_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_STAT_SDMA_STAT_MASK (0x0200u)
#define CSL_IMCOP_INTC_STAT_SDMA_STAT_SHIFT (0x0009u)
#define CSL_IMCOP_INTC_STAT_SDMA_STAT_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_STAT_COPC_STAT_MASK (0x0100u)
#define CSL_IMCOP_INTC_STAT_COPC_STAT_SHIFT (0x0008u)
#define CSL_IMCOP_INTC_STAT_COPC_STAT_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_STAT_RCNT_STAT_MASK (0x0080u)
#define CSL_IMCOP_INTC_STAT_RCNT_STAT_SHIFT (0x0007u)
#define CSL_IMCOP_INTC_STAT_RCNT_STAT_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_STAT_DCT_STAT_MASK (0x0040u)
#define CSL_IMCOP_INTC_STAT_DCT_STAT_SHIFT (0x0006u)
#define CSL_IMCOP_INTC_STAT_DCT_STAT_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_STAT_BSP_STAT_MASK (0x0020u)
#define CSL_IMCOP_INTC_STAT_BSP_STAT_SHIFT (0x0005u)
#define CSL_IMCOP_INTC_STAT_BSP_STAT_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_STAT_QIQ_STAT_MASK (0x0010u)
#define CSL_IMCOP_INTC_STAT_QIQ_STAT_SHIFT (0x0004u)
#define CSL_IMCOP_INTC_STAT_QIQ_STAT_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_STAT_VLD_STAT_MASK (0x0008u)
#define CSL_IMCOP_INTC_STAT_VLD_STAT_SHIFT (0x0003u)
#define CSL_IMCOP_INTC_STAT_VLD_STAT_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_STAT_BIM_STAT_MASK (0x0004u)
#define CSL_IMCOP_INTC_STAT_BIM_STAT_SHIFT (0x0002u)
#define CSL_IMCOP_INTC_STAT_BIM_STAT_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_STAT_IMX_STAT_MASK (0x0002u)
#define CSL_IMCOP_INTC_STAT_IMX_STAT_SHIFT (0x0001u)
#define CSL_IMCOP_INTC_STAT_IMX_STAT_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_STAT_VLCD_STAT_MASK (0x0001u)
#define CSL_IMCOP_INTC_STAT_VLCD_STAT_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_STAT_VLCD_STAT_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_STAT_RESETVAL     (0x0000u)

/* INTC_MSK */

#define CSL_IMCOP_INTC_MSK_ARM_MSK_MASK  (0x0400u)
#define CSL_IMCOP_INTC_MSK_ARM_MSK_SHIFT (0x000Au)
#define CSL_IMCOP_INTC_MSK_ARM_MSK_RESETVAL (0x0000u)

/*----ARM_MSK Tokens----*/
#define CSL_IMCOP_INTC_MSK_ARM_MSK_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_MSK_ARM_MSK_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_MSK_SDMA_MSK_MASK (0x0200u)
#define CSL_IMCOP_INTC_MSK_SDMA_MSK_SHIFT (0x0009u)
#define CSL_IMCOP_INTC_MSK_SDMA_MSK_RESETVAL (0x0000u)

/*----SDMA_MSK Tokens----*/
#define CSL_IMCOP_INTC_MSK_SDMA_MSK_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_MSK_SDMA_MSK_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_MSK_COPC_MSK_MASK (0x0100u)
#define CSL_IMCOP_INTC_MSK_COPC_MSK_SHIFT (0x0008u)
#define CSL_IMCOP_INTC_MSK_COPC_MSK_RESETVAL (0x0000u)

/*----COPC_MSK Tokens----*/
#define CSL_IMCOP_INTC_MSK_COPC_MSK_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_MSK_COPC_MSK_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_MSK_RCNT_MSK_MASK (0x0080u)
#define CSL_IMCOP_INTC_MSK_RCNT_MSK_SHIFT (0x0007u)
#define CSL_IMCOP_INTC_MSK_RCNT_MSK_RESETVAL (0x0000u)

/*----RCNT_MSK Tokens----*/
#define CSL_IMCOP_INTC_MSK_RCNT_MSK_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_MSK_RCNT_MSK_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_MSK_DCT_MSK_MASK  (0x0040u)
#define CSL_IMCOP_INTC_MSK_DCT_MSK_SHIFT (0x0006u)
#define CSL_IMCOP_INTC_MSK_DCT_MSK_RESETVAL (0x0000u)

/*----DCT_MSK Tokens----*/
#define CSL_IMCOP_INTC_MSK_DCT_MSK_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_MSK_DCT_MSK_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_MSK_BSP_MSK_MASK  (0x0020u)
#define CSL_IMCOP_INTC_MSK_BSP_MSK_SHIFT (0x0005u)
#define CSL_IMCOP_INTC_MSK_BSP_MSK_RESETVAL (0x0000u)

/*----BSP_MSK Tokens----*/
#define CSL_IMCOP_INTC_MSK_BSP_MSK_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_MSK_BSP_MSK_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_MSK_QIQ_MSK_MASK  (0x0010u)
#define CSL_IMCOP_INTC_MSK_QIQ_MSK_SHIFT (0x0004u)
#define CSL_IMCOP_INTC_MSK_QIQ_MSK_RESETVAL (0x0000u)

/*----QIQ_MSK Tokens----*/
#define CSL_IMCOP_INTC_MSK_QIQ_MSK_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_MSK_QIQ_MSK_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_MSK_VLD_MSK_MASK  (0x0008u)
#define CSL_IMCOP_INTC_MSK_VLD_MSK_SHIFT (0x0003u)
#define CSL_IMCOP_INTC_MSK_VLD_MSK_RESETVAL (0x0000u)

/*----VLD_MSK Tokens----*/
#define CSL_IMCOP_INTC_MSK_VLD_MSK_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_MSK_VLD_MSK_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_MSK_BIM_MSK_MASK  (0x0004u)
#define CSL_IMCOP_INTC_MSK_BIM_MSK_SHIFT (0x0002u)
#define CSL_IMCOP_INTC_MSK_BIM_MSK_RESETVAL (0x0000u)

/*----BIM_MSK Tokens----*/
#define CSL_IMCOP_INTC_MSK_BIM_MSK_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_MSK_BIM_MSK_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_MSK_IMX_MSK_MASK  (0x0002u)
#define CSL_IMCOP_INTC_MSK_IMX_MSK_SHIFT (0x0001u)
#define CSL_IMCOP_INTC_MSK_IMX_MSK_RESETVAL (0x0000u)

/*----IMX_MSK Tokens----*/
#define CSL_IMCOP_INTC_MSK_IMX_MSK_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_MSK_IMX_MSK_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_MSK_VLCD_MSK_MASK (0x0001u)
#define CSL_IMCOP_INTC_MSK_VLCD_MSK_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_MSK_VLCD_MSK_RESETVAL (0x0000u)

/*----VLCD_MSK Tokens----*/
#define CSL_IMCOP_INTC_MSK_VLCD_MSK_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_MSK_VLCD_MSK_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_MSK_RESETVAL      (0x0000u)

/* INTC_ARMCFG */

#define CSL_IMCOP_INTC_ARMCFG_PRI_MASK   (0xC000u)
#define CSL_IMCOP_INTC_ARMCFG_PRI_SHIFT  (0x000Eu)
#define CSL_IMCOP_INTC_ARMCFG_PRI_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_ARMCFG_INTVEC_MASK (0x3FFFu)
#define CSL_IMCOP_INTC_ARMCFG_INTVEC_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_ARMCFG_INTVEC_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_ARMCFG_RESETVAL   (0x0000u)

/* INTC_SDMACFG */

#define CSL_IMCOP_INTC_SDMACFG_PRI_MASK  (0xC000u)
#define CSL_IMCOP_INTC_SDMACFG_PRI_SHIFT (0x000Eu)
#define CSL_IMCOP_INTC_SDMACFG_PRI_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_SDMACFG_INTVEC_MASK (0x3FFFu)
#define CSL_IMCOP_INTC_SDMACFG_INTVEC_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_SDMACFG_INTVEC_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_SDMACFG_RESETVAL  (0x0000u)

/* INTC_COPCCFG */

#define CSL_IMCOP_INTC_COPCCFG_PRI_MASK  (0xC000u)
#define CSL_IMCOP_INTC_COPCCFG_PRI_SHIFT (0x000Eu)
#define CSL_IMCOP_INTC_COPCCFG_PRI_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_COPCCFG_INTVEC_MASK (0x3FFFu)
#define CSL_IMCOP_INTC_COPCCFG_INTVEC_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_COPCCFG_INTVEC_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_COPCCFG_RESETVAL  (0x0000u)

/* INTC_RCNTCFG */

#define CSL_IMCOP_INTC_RCNTCFG_PRI_MASK  (0xC000u)
#define CSL_IMCOP_INTC_RCNTCFG_PRI_SHIFT (0x000Eu)
#define CSL_IMCOP_INTC_RCNTCFG_PRI_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_RCNTCFG_INTVEC_MASK (0x3FFFu)
#define CSL_IMCOP_INTC_RCNTCFG_INTVEC_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_RCNTCFG_INTVEC_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_RCNTCFG_RESETVAL  (0x0000u)

/* INTC_DCTCFG */

#define CSL_IMCOP_INTC_DCTCFG_PRI_MASK   (0xC000u)
#define CSL_IMCOP_INTC_DCTCFG_PRI_SHIFT  (0x000Eu)
#define CSL_IMCOP_INTC_DCTCFG_PRI_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_DCTCFG_INTVEC_MASK (0x3FFFu)
#define CSL_IMCOP_INTC_DCTCFG_INTVEC_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_DCTCFG_INTVEC_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_DCTCFG_RESETVAL   (0x0000u)

/* INTC_BSPCFG */

#define CSL_IMCOP_INTC_BSPCFG_PRI_MASK   (0xC000u)
#define CSL_IMCOP_INTC_BSPCFG_PRI_SHIFT  (0x000Eu)
#define CSL_IMCOP_INTC_BSPCFG_PRI_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_BSPCFG_INTVEC_MASK (0x3FFFu)
#define CSL_IMCOP_INTC_BSPCFG_INTVEC_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_BSPCFG_INTVEC_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_BSPCFG_RESETVAL   (0x0000u)

/* INTC_QIQCFG */

#define CSL_IMCOP_INTC_QIQCFG_PRI_MASK   (0xC000u)
#define CSL_IMCOP_INTC_QIQCFG_PRI_SHIFT  (0x000Eu)
#define CSL_IMCOP_INTC_QIQCFG_PRI_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_QIQCFG_INTVEC_MASK (0x3FFFu)
#define CSL_IMCOP_INTC_QIQCFG_INTVEC_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_QIQCFG_INTVEC_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_QIQCFG_RESETVAL   (0x0000u)

/* INTC_VLDCFG */

#define CSL_IMCOP_INTC_VLDCFG_PRI_MASK   (0xC000u)
#define CSL_IMCOP_INTC_VLDCFG_PRI_SHIFT  (0x000Eu)
#define CSL_IMCOP_INTC_VLDCFG_PRI_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_VLDCFG_INTVEC_MASK (0x3FFFu)
#define CSL_IMCOP_INTC_VLDCFG_INTVEC_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_VLDCFG_INTVEC_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_VLDCFG_RESETVAL   (0x0000u)

/* INTC_BIMCFG */

#define CSL_IMCOP_INTC_BIMCFG_PRI_MASK   (0xC000u)
#define CSL_IMCOP_INTC_BIMCFG_PRI_SHIFT  (0x000Eu)
#define CSL_IMCOP_INTC_BIMCFG_PRI_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_BIMCFG_INTVEC_MASK (0x3FFFu)
#define CSL_IMCOP_INTC_BIMCFG_INTVEC_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_BIMCFG_INTVEC_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_BIMCFG_RESETVAL   (0x0000u)

/* INTC_IMXCFG */

#define CSL_IMCOP_INTC_IMXCFG_PRI_MASK   (0xC000u)
#define CSL_IMCOP_INTC_IMXCFG_PRI_SHIFT  (0x000Eu)
#define CSL_IMCOP_INTC_IMXCFG_PRI_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_IMXCFG_INTVEC_MASK (0x3FFFu)
#define CSL_IMCOP_INTC_IMXCFG_INTVEC_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_IMXCFG_INTVEC_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_IMXCFG_RESETVAL   (0x0000u)

/* INTC_VLCDCFG */

#define CSL_IMCOP_INTC_VLCDCFG_PRI_MASK  (0xC000u)
#define CSL_IMCOP_INTC_VLCDCFG_PRI_SHIFT (0x000Eu)
#define CSL_IMCOP_INTC_VLCDCFG_PRI_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_VLCDCFG_INTVEC_MASK (0x3FFFu)
#define CSL_IMCOP_INTC_VLCDCFG_INTVEC_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_VLCDCFG_INTVEC_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_VLCDCFG_RESETVAL  (0x0000u)

/* INTC_DBGC */

#define CSL_IMCOP_INTC_DBGC_EMU1IEN_MASK (0x0080u)
#define CSL_IMCOP_INTC_DBGC_EMU1IEN_SHIFT (0x0007u)
#define CSL_IMCOP_INTC_DBGC_EMU1IEN_RESETVAL (0x0000u)

/*----EMU1IEN Tokens----*/
#define CSL_IMCOP_INTC_DBGC_EMU1IEN_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_DBGC_EMU1IEN_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_DBGC_EMU0IEN_MASK (0x0040u)
#define CSL_IMCOP_INTC_DBGC_EMU0IEN_SHIFT (0x0006u)
#define CSL_IMCOP_INTC_DBGC_EMU0IEN_RESETVAL (0x0000u)

/*----EMU0IEN Tokens----*/
#define CSL_IMCOP_INTC_DBGC_EMU0IEN_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_DBGC_EMU0IEN_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_DBGC_EMU1OEN_MASK (0x0020u)
#define CSL_IMCOP_INTC_DBGC_EMU1OEN_SHIFT (0x0005u)
#define CSL_IMCOP_INTC_DBGC_EMU1OEN_RESETVAL (0x0000u)

/*----EMU1OEN Tokens----*/
#define CSL_IMCOP_INTC_DBGC_EMU1OEN_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_DBGC_EMU1OEN_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_DBGC_EMU0OEN_MASK (0x0010u)
#define CSL_IMCOP_INTC_DBGC_EMU0OEN_SHIFT (0x0004u)
#define CSL_IMCOP_INTC_DBGC_EMU0OEN_RESETVAL (0x0000u)

/*----EMU0OEN Tokens----*/
#define CSL_IMCOP_INTC_DBGC_EMU0OEN_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_DBGC_EMU0OEN_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_DBGC_RSM_MASK     (0x0008u)
#define CSL_IMCOP_INTC_DBGC_RSM_SHIFT    (0x0003u)
#define CSL_IMCOP_INTC_DBGC_RSM_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_DBGC_TMREN_MASK   (0x0004u)
#define CSL_IMCOP_INTC_DBGC_TMREN_SHIFT  (0x0002u)
#define CSL_IMCOP_INTC_DBGC_TMREN_RESETVAL (0x0000u)

/*----TMREN Tokens----*/
#define CSL_IMCOP_INTC_DBGC_TMREN_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_DBGC_TMREN_ENABLE (0x0001u)

#define CSL_IMCOP_INTC_DBGC_HWEN_MASK    (0x0002u)
#define CSL_IMCOP_INTC_DBGC_HWEN_SHIFT   (0x0001u)
#define CSL_IMCOP_INTC_DBGC_HWEN_RESETVAL (0x0000u)

/*----HWEN Tokens----*/
#define CSL_IMCOP_INTC_DBGC_HWEN_DISABLE (0x0000u)

#define CSL_IMCOP_INTC_DBGC_SWEN_MASK    (0x0001u)
#define CSL_IMCOP_INTC_DBGC_SWEN_SHIFT   (0x0000u)
#define CSL_IMCOP_INTC_DBGC_SWEN_RESETVAL (0x0000u)

/*----SWEN Tokens----*/
#define CSL_IMCOP_INTC_DBGC_SWEN_DISABLE (0x0000u)
#define CSL_IMCOP_INTC_DBGC_SWEN_ENABLE  (0x0001u)

#define CSL_IMCOP_INTC_DBGC_RESETVAL     (0x0000u)

/* INTC_HWBPA */

#define CSL_IMCOP_INTC_HWBPA_BPA_MASK    (0xFFFFu)
#define CSL_IMCOP_INTC_HWBPA_BPA_SHIFT   (0x0000u)
#define CSL_IMCOP_INTC_HWBPA_BPA_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_HWBPA_RESETVAL    (0x0000u)

/* INTC_BPST */

#define CSL_IMCOP_INTC_BPST_EMU1ISIG_MASK (0x0020u)
#define CSL_IMCOP_INTC_BPST_EMU1ISIG_SHIFT (0x0005u)
#define CSL_IMCOP_INTC_BPST_EMU1ISIG_RESETVAL (0x0001u)

#define CSL_IMCOP_INTC_BPST_EMU0ISIG_MASK (0x0010u)
#define CSL_IMCOP_INTC_BPST_EMU0ISIG_SHIFT (0x0004u)
#define CSL_IMCOP_INTC_BPST_EMU0ISIG_RESETVAL (0x0001u)

#define CSL_IMCOP_INTC_BPST_EMU1ST_MASK  (0x0008u)
#define CSL_IMCOP_INTC_BPST_EMU1ST_SHIFT (0x0003u)
#define CSL_IMCOP_INTC_BPST_EMU1ST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_BPST_EMU0ST_MASK  (0x0004u)
#define CSL_IMCOP_INTC_BPST_EMU0ST_SHIFT (0x0002u)
#define CSL_IMCOP_INTC_BPST_EMU0ST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_BPST_HWST_MASK    (0x0002u)
#define CSL_IMCOP_INTC_BPST_HWST_SHIFT   (0x0001u)
#define CSL_IMCOP_INTC_BPST_HWST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_BPST_SWST_MASK    (0x0001u)
#define CSL_IMCOP_INTC_BPST_SWST_SHIFT   (0x0000u)
#define CSL_IMCOP_INTC_BPST_SWST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_BPST_RESETVAL     (0x0030u)

/* INTC_TMR */

#define CSL_IMCOP_INTC_TMR_CNT_MASK      (0xFFFFu)
#define CSL_IMCOP_INTC_TMR_CNT_SHIFT     (0x0000u)
#define CSL_IMCOP_INTC_TMR_CNT_RESETVAL  (0x0000u)

#define CSL_IMCOP_INTC_TMR_RESETVAL      (0x0000u)

/* INTC_GENINT */

#define CSL_IMCOP_INTC_GENINT_GEN_INT_MASK (0x000Fu)
#define CSL_IMCOP_INTC_GENINT_GEN_INT_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_GENINT_GEN_INT_RESETVAL (0x0000u)

/*----GEN_INT Tokens----*/
#define CSL_IMCOP_INTC_GENINT_GEN_INT_IMXINTERRUPT (0x0000u)
#define CSL_IMCOP_INTC_GENINT_GEN_INT_VLCDINTERRUPT (0x0001u)
#define CSL_IMCOP_INTC_GENINT_GEN_INT_BABYIMXINTERRUPT (0x0002u)
#define CSL_IMCOP_INTC_GENINT_GEN_INT_DCTINTERRUPT (0x0003u)
#define CSL_IMCOP_INTC_GENINT_GEN_INT_QIQINTERRUPT (0x0004u)
#define CSL_IMCOP_INTC_GENINT_GEN_INT_BITSTREAMPARSERINTERRUPT (0x0005u)
#define CSL_IMCOP_INTC_GENINT_GEN_INT_VLDERRORINTERRUPT (0x0006u)
#define CSL_IMCOP_INTC_GENINT_GEN_INT_RATECNTINTERRUPT (0x0007u)
#define CSL_IMCOP_INTC_GENINT_GEN_INT_COPCINTERRUPT (0x0008u)

#define CSL_IMCOP_INTC_GENINT_RESETVAL   (0x0000u)

/* INTC_TESTINT */

#define CSL_IMCOP_INTC_TESTINT_TESTEN_MASK (0x0800u)
#define CSL_IMCOP_INTC_TESTINT_TESTEN_SHIFT (0x000Bu)
#define CSL_IMCOP_INTC_TESTINT_TESTEN_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_TESTINT_ARM_TEST_MASK (0x0400u)
#define CSL_IMCOP_INTC_TESTINT_ARM_TEST_SHIFT (0x000Au)
#define CSL_IMCOP_INTC_TESTINT_ARM_TEST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_TESTINT_SDMA_TEST_MASK (0x0200u)
#define CSL_IMCOP_INTC_TESTINT_SDMA_TEST_SHIFT (0x0009u)
#define CSL_IMCOP_INTC_TESTINT_SDMA_TEST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_TESTINT_COPC_TEST_MASK (0x0100u)
#define CSL_IMCOP_INTC_TESTINT_COPC_TEST_SHIFT (0x0008u)
#define CSL_IMCOP_INTC_TESTINT_COPC_TEST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_TESTINT_RCNT_TEST_MASK (0x0080u)
#define CSL_IMCOP_INTC_TESTINT_RCNT_TEST_SHIFT (0x0007u)
#define CSL_IMCOP_INTC_TESTINT_RCNT_TEST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_TESTINT_DCT_TEST_MASK (0x0040u)
#define CSL_IMCOP_INTC_TESTINT_DCT_TEST_SHIFT (0x0006u)
#define CSL_IMCOP_INTC_TESTINT_DCT_TEST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_TESTINT_BSP_TEST_MASK (0x0020u)
#define CSL_IMCOP_INTC_TESTINT_BSP_TEST_SHIFT (0x0005u)
#define CSL_IMCOP_INTC_TESTINT_BSP_TEST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_TESTINT_QIQ_TEST_MASK (0x0010u)
#define CSL_IMCOP_INTC_TESTINT_QIQ_TEST_SHIFT (0x0004u)
#define CSL_IMCOP_INTC_TESTINT_QIQ_TEST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_TESTINT_VLD_TEST_MASK (0x0008u)
#define CSL_IMCOP_INTC_TESTINT_VLD_TEST_SHIFT (0x0003u)
#define CSL_IMCOP_INTC_TESTINT_VLD_TEST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_TESTINT_BIM_TEST_MASK (0x0004u)
#define CSL_IMCOP_INTC_TESTINT_BIM_TEST_SHIFT (0x0002u)
#define CSL_IMCOP_INTC_TESTINT_BIM_TEST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_TESTINT_IMX_TEST_MASK (0x0002u)
#define CSL_IMCOP_INTC_TESTINT_IMX_TEST_SHIFT (0x0001u)
#define CSL_IMCOP_INTC_TESTINT_IMX_TEST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_TESTINT_VLCD_TEST_MASK (0x0001u)
#define CSL_IMCOP_INTC_TESTINT_VLCD_TEST_SHIFT (0x0000u)
#define CSL_IMCOP_INTC_TESTINT_VLCD_TEST_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_TESTINT_RESETVAL  (0x0000u)

/* INTC_EMU */

#define CSL_IMCOP_INTC_EMU_SOFT_MASK     (0x0002u)
#define CSL_IMCOP_INTC_EMU_SOFT_SHIFT    (0x0001u)
#define CSL_IMCOP_INTC_EMU_SOFT_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_EMU_FREE_MASK     (0x0001u)
#define CSL_IMCOP_INTC_EMU_FREE_SHIFT    (0x0000u)
#define CSL_IMCOP_INTC_EMU_FREE_RESETVAL (0x0000u)

#define CSL_IMCOP_INTC_EMU_RESETVAL      (0x0000u)

/* CFG_DMA */

#define CSL_IMCOP_CFG_DMA_RBUSY_MASK     (0x0200u)
#define CSL_IMCOP_CFG_DMA_RBUSY_SHIFT    (0x0009u)
#define CSL_IMCOP_CFG_DMA_RBUSY_RESETVAL (0x0000u)

/*----RBUSY Tokens----*/
#define CSL_IMCOP_CFG_DMA_RBUSY_DONE_IDLE (0x0000u)
#define CSL_IMCOP_CFG_DMA_RBUSY_BUSY     (0x0001u)

#define CSL_IMCOP_CFG_DMA_WBUSY_MASK     (0x0100u)
#define CSL_IMCOP_CFG_DMA_WBUSY_SHIFT    (0x0008u)
#define CSL_IMCOP_CFG_DMA_WBUSY_RESETVAL (0x0000u)

/*----WBUSY Tokens----*/
#define CSL_IMCOP_CFG_DMA_WBUSY_DONE_IDLE (0x0000u)
#define CSL_IMCOP_CFG_DMA_WBUSY_BUSY     (0x0001u)

#define CSL_IMCOP_CFG_DMA_WLEN_MASK      (0x000Fu)
#define CSL_IMCOP_CFG_DMA_WLEN_SHIFT     (0x0000u)
#define CSL_IMCOP_CFG_DMA_WLEN_RESETVAL  (0x0000u)

#define CSL_IMCOP_CFG_DMA_RESETVAL       (0x0000u)

/* CFG_RADDRL */

#define CSL_IMCOP_CFG_RADDRL_RADDRL_MASK (0xFFFFu)
#define CSL_IMCOP_CFG_RADDRL_RADDRL_SHIFT (0x0000u)
#define CSL_IMCOP_CFG_RADDRL_RADDRL_RESETVAL (0x0000u)

#define CSL_IMCOP_CFG_RADDRL_RESETVAL    (0x0000u)

/* CFG_RADDRH */

#define CSL_IMCOP_CFG_RADDRH_RADDRH_MASK (0xFFFFu)
#define CSL_IMCOP_CFG_RADDRH_RADDRH_SHIFT (0x0000u)
#define CSL_IMCOP_CFG_RADDRH_RADDRH_RESETVAL (0x0000u)

#define CSL_IMCOP_CFG_RADDRH_RESETVAL    (0x0000u)

/* CFG_WADDRL */

#define CSL_IMCOP_CFG_WADDRL_WADDRL_MASK (0xFFFFu)
#define CSL_IMCOP_CFG_WADDRL_WADDRL_SHIFT (0x0000u)
#define CSL_IMCOP_CFG_WADDRL_WADDRL_RESETVAL (0x0000u)

#define CSL_IMCOP_CFG_WADDRL_RESETVAL    (0x0000u)

/* CFG_WADDRH */

#define CSL_IMCOP_CFG_WADDRH_WADDRH_MASK (0xFFFFu)
#define CSL_IMCOP_CFG_WADDRH_WADDRH_SHIFT (0x0000u)
#define CSL_IMCOP_CFG_WADDRH_WADDRH_RESETVAL (0x0000u)

#define CSL_IMCOP_CFG_WADDRH_RESETVAL    (0x0000u)

/* CFG_RDATAL */

#define CSL_IMCOP_CFG_RDATAL_RDATAL_MASK (0xFFFFu)
#define CSL_IMCOP_CFG_RDATAL_RDATAL_SHIFT (0x0000u)
#define CSL_IMCOP_CFG_RDATAL_RDATAL_RESETVAL (0x0000u)

#define CSL_IMCOP_CFG_RDATAL_RESETVAL    (0x0000u)

/* CFG_RDATAH */

#define CSL_IMCOP_CFG_RDATAH_RDATAH_MASK (0xFFFFu)
#define CSL_IMCOP_CFG_RDATAH_RDATAH_SHIFT (0x0000u)
#define CSL_IMCOP_CFG_RDATAH_RDATAH_RESETVAL (0x0000u)

#define CSL_IMCOP_CFG_RDATAH_RESETVAL    (0x0000u)

/* CFG_WDATA */

#define CSL_IMCOP_CFG_WDATA_WDATA_MASK   (0xFFFFu)
#define CSL_IMCOP_CFG_WDATA_WDATA_SHIFT  (0x0000u)
#define CSL_IMCOP_CFG_WDATA_WDATA_RESETVAL (0x0000u)

#define CSL_IMCOP_CFG_WDATA_RESETVAL     (0x0000u)

#endif
