#ifndef _CSLR_VLCD_1_H_
#define _CSLR_VLCD_1_H_
/*********************************************************************
 * Copyright (C) 2003-2004 Texas Instruments Incorporated. 
 * All Rights Reserved 
 *********************************************************************/
 /** \file cslr_vlcd_1.h
 * 
 * \brief This file contains the Register Desciptions for VLCD
 * 
 *********************************************************************/

#include <cslr.h>

#include <tistdtypes.h>

/**************************************************************************\
* Register Overlay Structure
\**************************************************************************/
typedef struct  {
    volatile Uint16 START;
    volatile Uint16 MODE;
    volatile Uint16 QIN_ADDR;
    volatile Uint16 QOUT_ADDR;
    volatile Uint16 IQIN_ADDR;
    volatile Uint16 IQOUT_ADDR;
    volatile Uint16 VLCDIN_ADDR;
    volatile Uint16 VLCDOUT_ADDR;
    volatile Uint16 DC_PRED0;
    volatile Uint16 DC_PRED1;
    volatile Uint16 DC_PRED2;
    volatile Uint16 DC_PRED3;
    volatile Uint16 DC_PRED4;
    volatile Uint16 DC_PRED5;
    volatile Uint16 IDC_PRED0;
    volatile Uint16 IDC_PRED1;
    volatile Uint16 IDC_PRED2;
    volatile Uint16 IDC_PRED3;
    volatile Uint16 IDC_PRED4;
    volatile Uint16 IDC_PRED5;
    volatile Uint16 MPEG_INVQ;
    volatile Uint16 MPEG_Q;
    volatile Uint16 MPEG_DELTA_Q;
    volatile Uint16 MPEG_DELTA_IQ;
    volatile Uint16 MPEG_THRED;
    volatile Uint16 MPEG_CBP;
    volatile Uint16 LUMA_VECTOR;
    volatile Uint16 HUFFTAB_DCY;
    volatile Uint16 HUFFTAB_DCUV;
    volatile Uint16 HUFFTAB_AC0;
    volatile Uint16 HUFFTAB_AC1;
    volatile Uint16 OFLEV_MAXOTAB;
    volatile Uint16 OFLEV_MAX1TAB;
    volatile Uint16 CTLTAB_DCY;
    volatile Uint16 CTLTAB_DCUV;
    volatile Uint16 CTLTAB_AC0;
    volatile Uint16 CTLTAB_AC1;
    volatile Uint16 OFFSET_DCY;
    volatile Uint16 OFFSET_DCUV;
    volatile Uint16 OFFSET_AC0;
    volatile Uint16 OFFSET_AC1;
    volatile Uint16 SYMTAB_DCY;
    volatile Uint16 SYMTAB_DCUV;
    volatile Uint16 SYMTAB_AC0;
    volatile Uint16 SYMTAB_AC1;
    volatile Uint16 CTL;
    volatile Uint16 VLD_NRBIT_DC;
    volatile Uint16 VLD_NRBIT_AC;
    volatile Uint16 BITS_BPTR;
    volatile Uint16 BITS_WORD;
    volatile Uint16 BYTE_ALIGN;
    volatile Uint16 HEAD_ADDR;
    volatile Uint16 HEAD_NUM;
    volatile Uint16 QIQ_CONFIG0;
    volatile Uint16 QIQ_CONFIG1;
    volatile Uint16 QIQ_CONFIG2;
    volatile Uint16 QIQ_CONFIG3;
    volatile Uint16 QIQ_CONFIG4;
    volatile Uint16 QIQ_CONFIG5;
    volatile Uint16 VLD_ERRCTL;
    volatile Uint16 VLD_ERRSTAT;
    volatile Uint16 RING_START;
    volatile Uint16 RING_END;
    volatile Uint16 CLKCTRL;
    volatile Uint16 VLD_PREFIX_DC;
    volatile Uint16 VLD_PREFIX_AC;
    volatile Uint16 WMV9_CFG;
    volatile Uint16 FIRST_FRAME;
    volatile Uint16 H264_MODE;
    volatile Uint16 NRBITS_THRED;
} CSL_VlcdRegs;

/**************************************************************************\
* Field Definition Macros
\**************************************************************************/

/* START */

#define CSL_VLCD_START_INT_MASK          (0x0002u)
#define CSL_VLCD_START_INT_SHIFT         (0x0001u)
#define CSL_VLCD_START_INT_RESETVAL      (0x0000u)

/*----INT Tokens----*/
#define CSL_VLCD_START_INT_DISABLE       (0x0000u)
#define CSL_VLCD_START_INT_ENABLE        (0x0001u)

#define CSL_VLCD_START_GO_MASK           (0x0001u)
#define CSL_VLCD_START_GO_SHIFT          (0x0000u)
#define CSL_VLCD_START_GO_RESETVAL       (0x0000u)

#define CSL_VLCD_START_RESETVAL          (0x0000u)

/* MODE */

#define CSL_VLCD_MODE_MPEGRND_MASK       (0x8000u)
#define CSL_VLCD_MODE_MPEGRND_SHIFT      (0x000Fu)
#define CSL_VLCD_MODE_MPEGRND_RESETVAL   (0x0000u)

/*----MPEGRND Tokens----*/
#define CSL_VLCD_MODE_MPEGRND_OFF        (0x0000u)
#define CSL_VLCD_MODE_MPEGRND_ON         (0x0001u)

#define CSL_VLCD_MODE_NUMBLKS_MASK       (0x7000u)
#define CSL_VLCD_MODE_NUMBLKS_SHIFT      (0x000Cu)
#define CSL_VLCD_MODE_NUMBLKS_RESETVAL   (0x0000u)

#define CSL_VLCD_MODE_JPEGSYNC_MASK      (0x0800u)
#define CSL_VLCD_MODE_JPEGSYNC_SHIFT     (0x000Bu)
#define CSL_VLCD_MODE_JPEGSYNC_RESETVAL  (0x0000u)

/*----JPEGSYNC Tokens----*/
#define CSL_VLCD_MODE_JPEGSYNC_OFF       (0x0000u)
#define CSL_VLCD_MODE_JPEGSYNC_ON        (0x0001u)

#define CSL_VLCD_MODE_MPEGTYPE_MASK      (0x0400u)
#define CSL_VLCD_MODE_MPEGTYPE_SHIFT     (0x000Au)
#define CSL_VLCD_MODE_MPEGTYPE_RESETVAL  (0x0000u)

/*----MPEGTYPE Tokens----*/
#define CSL_VLCD_MODE_MPEGTYPE_I_P_B_PICTURE (0x0000u)
#define CSL_VLCD_MODE_MPEGTYPE_D_PICTURE (0x0001u)

#define CSL_VLCD_MODE_SCAN_MASK          (0x0300u)
#define CSL_VLCD_MODE_SCAN_SHIFT         (0x0008u)
#define CSL_VLCD_MODE_SCAN_RESETVAL      (0x0000u)

/*----SCAN Tokens----*/
#define CSL_VLCD_MODE_SCAN_LINEARSCAN    (0x0000u)
#define CSL_VLCD_MODE_SCAN_ZIGZAGSCAN    (0x0001u)
#define CSL_VLCD_MODE_SCAN_ALTERNATE_VERTICALSCAN (0x0002u)
#define CSL_VLCD_MODE_SCAN_ALTERNATE_HORIZONTALSCAN (0x0003u)

#define CSL_VLCD_MODE_MPEGINTRA_MASK     (0x0080u)
#define CSL_VLCD_MODE_MPEGINTRA_SHIFT    (0x0007u)
#define CSL_VLCD_MODE_MPEGINTRA_RESETVAL (0x0000u)

/*----MPEGINTRA Tokens----*/
#define CSL_VLCD_MODE_MPEGINTRA_NON_INTRAMB (0x0000u)
#define CSL_VLCD_MODE_MPEGINTRA_INTRAMB  (0x0001u)

#define CSL_VLCD_MODE_INTRAVLC_MASK      (0x0040u)
#define CSL_VLCD_MODE_INTRAVLC_SHIFT     (0x0006u)
#define CSL_VLCD_MODE_INTRAVLC_RESETVAL  (0x0000u)

#define CSL_VLCD_MODE_MODESEL_MASK       (0x0030u)
#define CSL_VLCD_MODE_MODESEL_SHIFT      (0x0004u)
#define CSL_VLCD_MODE_MODESEL_RESETVAL   (0x0000u)

/*----MODESEL Tokens----*/
#define CSL_VLCD_MODE_MODESEL_JPEG       (0x0000u)
#define CSL_VLCD_MODE_MODESEL_MPEG1      (0x0001u)
#define CSL_VLCD_MODE_MODESEL_MPEG4      (0x0002u)
#define CSL_VLCD_MODE_MODESEL_H263       (0x0003u)

#define CSL_VLCD_MODE_QMPEGTYPE_MASK     (0x0008u)
#define CSL_VLCD_MODE_QMPEGTYPE_SHIFT    (0x0003u)
#define CSL_VLCD_MODE_QMPEGTYPE_RESETVAL (0x0000u)

/*----QMPEGTYPE Tokens----*/
#define CSL_VLCD_MODE_QMPEGTYPE_TYPE0    (0x0000u)
#define CSL_VLCD_MODE_QMPEGTYPE_TYPE1    (0x0001u)

#define CSL_VLCD_MODE_FUNC_MASK          (0x0007u)
#define CSL_VLCD_MODE_FUNC_SHIFT         (0x0000u)
#define CSL_VLCD_MODE_FUNC_RESETVAL      (0x0000u)

/*----FUNC Tokens----*/
#define CSL_VLCD_MODE_FUNC_Q             (0x0000u)
#define CSL_VLCD_MODE_FUNC_IQ            (0x0001u)
#define CSL_VLCD_MODE_FUNC_VLC           (0x0002u)
#define CSL_VLCD_MODE_FUNC_VLD           (0x0003u)
#define CSL_VLCD_MODE_FUNC_Q_IQ          (0x0004u)
#define CSL_VLCD_MODE_FUNC_Q_VLC         (0x0005u)
#define CSL_VLCD_MODE_FUNC_Q_IQ_VLC      (0x0006u)
#define CSL_VLCD_MODE_FUNC_VLD_IQ        (0x0007u)

#define CSL_VLCD_MODE_RESETVAL           (0x0000u)

/* QIN_ADDR */

#define CSL_VLCD_QIN_ADDR_ADDR_MASK      (0x0FFFu)
#define CSL_VLCD_QIN_ADDR_ADDR_SHIFT     (0x0000u)
#define CSL_VLCD_QIN_ADDR_ADDR_RESETVAL  (0x0000u)

#define CSL_VLCD_QIN_ADDR_RESETVAL       (0x0000u)

/* QOUT_ADDR */

#define CSL_VLCD_QOUT_ADDR_ADDR_MASK     (0x0FFFu)
#define CSL_VLCD_QOUT_ADDR_ADDR_SHIFT    (0x0000u)
#define CSL_VLCD_QOUT_ADDR_ADDR_RESETVAL (0x0000u)

#define CSL_VLCD_QOUT_ADDR_RESETVAL      (0x0000u)

/* IQIN_ADDR */

#define CSL_VLCD_IQIN_ADDR_ADDR_MASK     (0x0FFFu)
#define CSL_VLCD_IQIN_ADDR_ADDR_SHIFT    (0x0000u)
#define CSL_VLCD_IQIN_ADDR_ADDR_RESETVAL (0x0000u)

#define CSL_VLCD_IQIN_ADDR_RESETVAL      (0x0000u)

/* IQOUT_ADDR */

#define CSL_VLCD_IQOUT_ADDR_ADDR_MASK    (0x0FFFu)
#define CSL_VLCD_IQOUT_ADDR_ADDR_SHIFT   (0x0000u)
#define CSL_VLCD_IQOUT_ADDR_ADDR_RESETVAL (0x0000u)

#define CSL_VLCD_IQOUT_ADDR_RESETVAL     (0x0000u)

/* VLCDIN_ADDR */

#define CSL_VLCD_VLCDIN_ADDR_ADDR_MASK   (0x0FFFu)
#define CSL_VLCD_VLCDIN_ADDR_ADDR_SHIFT  (0x0000u)
#define CSL_VLCD_VLCDIN_ADDR_ADDR_RESETVAL (0x0000u)

#define CSL_VLCD_VLCDIN_ADDR_RESETVAL    (0x0000u)

/* VLCDOUT_ADDR */

#define CSL_VLCD_VLCDOUT_ADDR_ADDR_MASK  (0x0FFFu)
#define CSL_VLCD_VLCDOUT_ADDR_ADDR_SHIFT (0x0000u)
#define CSL_VLCD_VLCDOUT_ADDR_ADDR_RESETVAL (0x0000u)

#define CSL_VLCD_VLCDOUT_ADDR_RESETVAL   (0x0000u)

/* DC_PRED0 */

#define CSL_VLCD_DC_PRED0_PRED0_MASK     (0x0FFFu)
#define CSL_VLCD_DC_PRED0_PRED0_SHIFT    (0x0000u)
#define CSL_VLCD_DC_PRED0_PRED0_RESETVAL (0x0000u)

#define CSL_VLCD_DC_PRED0_RESETVAL       (0x0000u)

/* DC_PRED1 */

#define CSL_VLCD_DC_PRED1_PRED1_MASK     (0x0FFFu)
#define CSL_VLCD_DC_PRED1_PRED1_SHIFT    (0x0000u)
#define CSL_VLCD_DC_PRED1_PRED1_RESETVAL (0x0000u)

#define CSL_VLCD_DC_PRED1_RESETVAL       (0x0000u)

/* DC_PRED2 */

#define CSL_VLCD_DC_PRED2_PRED2_MASK     (0x0FFFu)
#define CSL_VLCD_DC_PRED2_PRED2_SHIFT    (0x0000u)
#define CSL_VLCD_DC_PRED2_PRED2_RESETVAL (0x0000u)

#define CSL_VLCD_DC_PRED2_RESETVAL       (0x0000u)

/* DC_PRED3 */

#define CSL_VLCD_DC_PRED3_PRED3_MASK     (0x0FFFu)
#define CSL_VLCD_DC_PRED3_PRED3_SHIFT    (0x0000u)
#define CSL_VLCD_DC_PRED3_PRED3_RESETVAL (0x0000u)

#define CSL_VLCD_DC_PRED3_RESETVAL       (0x0000u)

/* DC_PRED4 */

#define CSL_VLCD_DC_PRED4_PRED4_MASK     (0x0FFFu)
#define CSL_VLCD_DC_PRED4_PRED4_SHIFT    (0x0000u)
#define CSL_VLCD_DC_PRED4_PRED4_RESETVAL (0x0000u)

#define CSL_VLCD_DC_PRED4_RESETVAL       (0x0000u)

/* DC_PRED5 */

#define CSL_VLCD_DC_PRED5_PRED5_MASK     (0x0FFFu)
#define CSL_VLCD_DC_PRED5_PRED5_SHIFT    (0x0000u)
#define CSL_VLCD_DC_PRED5_PRED5_RESETVAL (0x0000u)

#define CSL_VLCD_DC_PRED5_RESETVAL       (0x0000u)

/* IDC_PRED0 */

#define CSL_VLCD_IDC_PRED0_IPRED0_MASK   (0x0FFFu)
#define CSL_VLCD_IDC_PRED0_IPRED0_SHIFT  (0x0000u)
#define CSL_VLCD_IDC_PRED0_IPRED0_RESETVAL (0x0000u)

#define CSL_VLCD_IDC_PRED0_RESETVAL      (0x0000u)

/* IDC_PRED1 */

#define CSL_VLCD_IDC_PRED1_IPRED1_MASK   (0x0FFFu)
#define CSL_VLCD_IDC_PRED1_IPRED1_SHIFT  (0x0000u)
#define CSL_VLCD_IDC_PRED1_IPRED1_RESETVAL (0x0000u)

#define CSL_VLCD_IDC_PRED1_RESETVAL      (0x0000u)

/* IDC_PRED2 */

#define CSL_VLCD_IDC_PRED2_IPRED2_MASK   (0x0FFFu)
#define CSL_VLCD_IDC_PRED2_IPRED2_SHIFT  (0x0000u)
#define CSL_VLCD_IDC_PRED2_IPRED2_RESETVAL (0x0000u)

#define CSL_VLCD_IDC_PRED2_RESETVAL      (0x0000u)

/* IDC_PRED3 */

#define CSL_VLCD_IDC_PRED3_IPRED3_MASK   (0x0FFFu)
#define CSL_VLCD_IDC_PRED3_IPRED3_SHIFT  (0x0000u)
#define CSL_VLCD_IDC_PRED3_IPRED3_RESETVAL (0x0000u)

#define CSL_VLCD_IDC_PRED3_RESETVAL      (0x0000u)

/* IDC_PRED4 */

#define CSL_VLCD_IDC_PRED4_IPRED4_MASK   (0x0FFFu)
#define CSL_VLCD_IDC_PRED4_IPRED4_SHIFT  (0x0000u)
#define CSL_VLCD_IDC_PRED4_IPRED4_RESETVAL (0x0000u)

#define CSL_VLCD_IDC_PRED4_RESETVAL      (0x0000u)

/* IDC_PRED5 */

#define CSL_VLCD_IDC_PRED5_IPRED5_MASK   (0x0FFFu)
#define CSL_VLCD_IDC_PRED5_IPRED5_SHIFT  (0x0000u)
#define CSL_VLCD_IDC_PRED5_IPRED5_RESETVAL (0x0000u)

#define CSL_VLCD_IDC_PRED5_RESETVAL      (0x0000u)

/* MPEG_INVQ */

#define CSL_VLCD_MPEG_INVQ_MPEG_INVQ_MASK (0xFFFFu)
#define CSL_VLCD_MPEG_INVQ_MPEG_INVQ_SHIFT (0x0000u)
#define CSL_VLCD_MPEG_INVQ_MPEG_INVQ_RESETVAL (0x0000u)

#define CSL_VLCD_MPEG_INVQ_RESETVAL      (0x0000u)

/* MPEG_Q */

#define CSL_VLCD_MPEG_Q_MQ_MASK          (0x00FFu)
#define CSL_VLCD_MPEG_Q_MQ_SHIFT         (0x0000u)
#define CSL_VLCD_MPEG_Q_MQ_RESETVAL      (0x0000u)

#define CSL_VLCD_MPEG_Q_RESETVAL         (0x0000u)

/* MPEG_DELTA_Q */

#define CSL_VLCD_MPEG_DELTA_Q_MDELQ_MASK (0x01FFu)
#define CSL_VLCD_MPEG_DELTA_Q_MDELQ_SHIFT (0x0000u)
#define CSL_VLCD_MPEG_DELTA_Q_MDELQ_RESETVAL (0x0000u)

#define CSL_VLCD_MPEG_DELTA_Q_RESETVAL   (0x0000u)

/* MPEG_DELTA_IQ */

#define CSL_VLCD_MPEG_DELTA_IQ_MDELIQ_MASK (0x01FFu)
#define CSL_VLCD_MPEG_DELTA_IQ_MDELIQ_SHIFT (0x0000u)
#define CSL_VLCD_MPEG_DELTA_IQ_MDELIQ_RESETVAL (0x0000u)

#define CSL_VLCD_MPEG_DELTA_IQ_RESETVAL  (0x0000u)

/* MPEG_THRED */

#define CSL_VLCD_MPEG_THRED_MTHRED_MASK  (0x0FFFu)
#define CSL_VLCD_MPEG_THRED_MTHRED_SHIFT (0x0000u)
#define CSL_VLCD_MPEG_THRED_MTHRED_RESETVAL (0x0000u)

#define CSL_VLCD_MPEG_THRED_RESETVAL     (0x0000u)

/* MPEG_CBP */

#define CSL_VLCD_MPEG_CBP_CBPON_MASK     (0x0100u)
#define CSL_VLCD_MPEG_CBP_CBPON_SHIFT    (0x0008u)
#define CSL_VLCD_MPEG_CBP_CBPON_RESETVAL (0x0000u)

/*----CBPON Tokens----*/
#define CSL_VLCD_MPEG_CBP_CBPON_CBP_DETECT_OFF (0x0000u)
#define CSL_VLCD_MPEG_CBP_CBPON_CBP_DETECT_ON (0x0001u)

#define CSL_VLCD_MPEG_CBP_CBP_MASK       (0x003Fu)
#define CSL_VLCD_MPEG_CBP_CBP_SHIFT      (0x0000u)
#define CSL_VLCD_MPEG_CBP_CBP_RESETVAL   (0x0000u)

#define CSL_VLCD_MPEG_CBP_RESETVAL       (0x0000u)

/* LUMA_VECTOR */

#define CSL_VLCD_LUMA_VECTOR_LUMVECT_MASK (0x003Fu)
#define CSL_VLCD_LUMA_VECTOR_LUMVECT_SHIFT (0x0000u)
#define CSL_VLCD_LUMA_VECTOR_LUMVECT_RESETVAL (0x0000u)

#define CSL_VLCD_LUMA_VECTOR_RESETVAL    (0x0000u)

/* HUFFTAB_DCY */

#define CSL_VLCD_HUFFTAB_DCY_HDCY_MASK   (0x07FFu)
#define CSL_VLCD_HUFFTAB_DCY_HDCY_SHIFT  (0x0000u)
#define CSL_VLCD_HUFFTAB_DCY_HDCY_RESETVAL (0x0000u)

#define CSL_VLCD_HUFFTAB_DCY_RESETVAL    (0x0000u)

/* HUFFTAB_DCUV */

#define CSL_VLCD_HUFFTAB_DCUV_HDCUV_MASK (0x07FFu)
#define CSL_VLCD_HUFFTAB_DCUV_HDCUV_SHIFT (0x0000u)
#define CSL_VLCD_HUFFTAB_DCUV_HDCUV_RESETVAL (0x0000u)

#define CSL_VLCD_HUFFTAB_DCUV_RESETVAL   (0x0000u)

/* HUFFTAB_AC0 */

#define CSL_VLCD_HUFFTAB_AC0_HAC0_MASK   (0x07FFu)
#define CSL_VLCD_HUFFTAB_AC0_HAC0_SHIFT  (0x0000u)
#define CSL_VLCD_HUFFTAB_AC0_HAC0_RESETVAL (0x0000u)

#define CSL_VLCD_HUFFTAB_AC0_RESETVAL    (0x0000u)

/* HUFFTAB_AC1 */

#define CSL_VLCD_HUFFTAB_AC1_HAC1_MASK   (0x07FFu)
#define CSL_VLCD_HUFFTAB_AC1_HAC1_SHIFT  (0x0000u)
#define CSL_VLCD_HUFFTAB_AC1_HAC1_RESETVAL (0x0000u)

#define CSL_VLCD_HUFFTAB_AC1_RESETVAL    (0x0000u)

/* OFLEV_MAXOTAB */

#define CSL_VLCD_OFLEV_MAXOTAB_MAX0_MASK (0x07FFu)
#define CSL_VLCD_OFLEV_MAXOTAB_MAX0_SHIFT (0x0000u)
#define CSL_VLCD_OFLEV_MAXOTAB_MAX0_RESETVAL (0x0000u)

#define CSL_VLCD_OFLEV_MAXOTAB_RESETVAL  (0x0000u)

/* OFLEV_MAX1TAB */

#define CSL_VLCD_OFLEV_MAX1TAB_MAX1_MASK (0x07FFu)
#define CSL_VLCD_OFLEV_MAX1TAB_MAX1_SHIFT (0x0000u)
#define CSL_VLCD_OFLEV_MAX1TAB_MAX1_RESETVAL (0x0000u)

#define CSL_VLCD_OFLEV_MAX1TAB_RESETVAL  (0x0000u)

/* CTLTAB_DCY */

#define CSL_VLCD_CTLTAB_DCY_CDCY_MASK    (0x07FFu)
#define CSL_VLCD_CTLTAB_DCY_CDCY_SHIFT   (0x0000u)
#define CSL_VLCD_CTLTAB_DCY_CDCY_RESETVAL (0x0000u)

#define CSL_VLCD_CTLTAB_DCY_RESETVAL     (0x0000u)

/* CTLTAB_DCUV */

#define CSL_VLCD_CTLTAB_DCUV_CDCUV_MASK  (0x07FFu)
#define CSL_VLCD_CTLTAB_DCUV_CDCUV_SHIFT (0x0000u)
#define CSL_VLCD_CTLTAB_DCUV_CDCUV_RESETVAL (0x0000u)

#define CSL_VLCD_CTLTAB_DCUV_RESETVAL    (0x0000u)

/* CTLTAB_AC0 */

#define CSL_VLCD_CTLTAB_AC0_CAC0_MASK    (0x07FFu)
#define CSL_VLCD_CTLTAB_AC0_CAC0_SHIFT   (0x0000u)
#define CSL_VLCD_CTLTAB_AC0_CAC0_RESETVAL (0x0000u)

#define CSL_VLCD_CTLTAB_AC0_RESETVAL     (0x0000u)

/* CTLTAB_AC1 */

#define CSL_VLCD_CTLTAB_AC1_CAC1_MASK    (0x07FFu)
#define CSL_VLCD_CTLTAB_AC1_CAC1_SHIFT   (0x0000u)
#define CSL_VLCD_CTLTAB_AC1_CAC1_RESETVAL (0x0000u)

#define CSL_VLCD_CTLTAB_AC1_RESETVAL     (0x0000u)

/* OFFSET_DCY */

#define CSL_VLCD_OFFSET_DCY_ODCY_MASK    (0x07FFu)
#define CSL_VLCD_OFFSET_DCY_ODCY_SHIFT   (0x0000u)
#define CSL_VLCD_OFFSET_DCY_ODCY_RESETVAL (0x0000u)

#define CSL_VLCD_OFFSET_DCY_RESETVAL     (0x0000u)

/* OFFSET_DCUV */

#define CSL_VLCD_OFFSET_DCUV_ODCUV_MASK  (0x07FFu)
#define CSL_VLCD_OFFSET_DCUV_ODCUV_SHIFT (0x0000u)
#define CSL_VLCD_OFFSET_DCUV_ODCUV_RESETVAL (0x0000u)

#define CSL_VLCD_OFFSET_DCUV_RESETVAL    (0x0000u)

/* OFFSET_AC0 */

#define CSL_VLCD_OFFSET_AC0_OAC0_MASK    (0x07FFu)
#define CSL_VLCD_OFFSET_AC0_OAC0_SHIFT   (0x0000u)
#define CSL_VLCD_OFFSET_AC0_OAC0_RESETVAL (0x0000u)

#define CSL_VLCD_OFFSET_AC0_RESETVAL     (0x0000u)

/* OFFSET_AC1 */

#define CSL_VLCD_OFFSET_AC1_OAC1_MASK    (0x07FFu)
#define CSL_VLCD_OFFSET_AC1_OAC1_SHIFT   (0x0000u)
#define CSL_VLCD_OFFSET_AC1_OAC1_RESETVAL (0x0000u)

#define CSL_VLCD_OFFSET_AC1_RESETVAL     (0x0000u)

/* SYMTAB_DCY */

#define CSL_VLCD_SYMTAB_DCY_SDCY_MASK    (0x07FFu)
#define CSL_VLCD_SYMTAB_DCY_SDCY_SHIFT   (0x0000u)
#define CSL_VLCD_SYMTAB_DCY_SDCY_RESETVAL (0x0000u)

#define CSL_VLCD_SYMTAB_DCY_RESETVAL     (0x0000u)

/* SYMTAB_DCUV */

#define CSL_VLCD_SYMTAB_DCUV_SDCUV_MASK  (0x07FFu)
#define CSL_VLCD_SYMTAB_DCUV_SDCUV_SHIFT (0x0000u)
#define CSL_VLCD_SYMTAB_DCUV_SDCUV_RESETVAL (0x0000u)

#define CSL_VLCD_SYMTAB_DCUV_RESETVAL    (0x0000u)

/* SYMTAB_AC0 */

#define CSL_VLCD_SYMTAB_AC0_SAC0_MASK    (0x07FFu)
#define CSL_VLCD_SYMTAB_AC0_SAC0_SHIFT   (0x0000u)
#define CSL_VLCD_SYMTAB_AC0_SAC0_RESETVAL (0x0000u)

#define CSL_VLCD_SYMTAB_AC0_RESETVAL     (0x0000u)

/* SYMTAB_AC1 */

#define CSL_VLCD_SYMTAB_AC1_SAC1_MASK    (0x07FFu)
#define CSL_VLCD_SYMTAB_AC1_SAC1_SHIFT   (0x0000u)
#define CSL_VLCD_SYMTAB_AC1_SAC1_RESETVAL (0x0000u)

#define CSL_VLCD_SYMTAB_AC1_RESETVAL     (0x0000u)

/* CTL */

#define CSL_VLCD_CTL_UVLD_MASK           (0x0100u)
#define CSL_VLCD_CTL_UVLD_SHIFT          (0x0008u)
#define CSL_VLCD_CTL_UVLD_RESETVAL       (0x0000u)

/*----UVLD Tokens----*/
#define CSL_VLCD_CTL_UVLD_VLD            (0x0000u)
#define CSL_VLCD_CTL_UVLD_RVLC           (0x0001u)

#define CSL_VLCD_CTL_DCYLEAD_MASK        (0x0080u)
#define CSL_VLCD_CTL_DCYLEAD_SHIFT       (0x0007u)
#define CSL_VLCD_CTL_DCYLEAD_RESETVAL    (0x0000u)

#define CSL_VLCD_CTL_DCUVLEAD_MASK       (0x0040u)
#define CSL_VLCD_CTL_DCUVLEAD_SHIFT      (0x0006u)
#define CSL_VLCD_CTL_DCUVLEAD_RESETVAL   (0x0000u)

#define CSL_VLCD_CTL_AC0LEAD_MASK        (0x0020u)
#define CSL_VLCD_CTL_AC0LEAD_SHIFT       (0x0005u)
#define CSL_VLCD_CTL_AC0LEAD_RESETVAL    (0x0000u)

#define CSL_VLCD_CTL_AC1LEAD_MASK        (0x0010u)
#define CSL_VLCD_CTL_AC1LEAD_SHIFT       (0x0004u)
#define CSL_VLCD_CTL_AC1LEAD_RESETVAL    (0x0000u)

#define CSL_VLCD_CTL_DCYSYMLEN_MASK      (0x0008u)
#define CSL_VLCD_CTL_DCYSYMLEN_SHIFT     (0x0003u)
#define CSL_VLCD_CTL_DCYSYMLEN_RESETVAL  (0x0000u)

/*----DCYSYMLEN Tokens----*/
#define CSL_VLCD_CTL_DCYSYMLEN_12BITSYM  (0x0000u)
#define CSL_VLCD_CTL_DCYSYMLEN_11BITSYM  (0x0001u)

#define CSL_VLCD_CTL_DCUVSYMLEN_MASK     (0x0004u)
#define CSL_VLCD_CTL_DCUVSYMLEN_SHIFT    (0x0002u)
#define CSL_VLCD_CTL_DCUVSYMLEN_RESETVAL (0x0000u)

/*----DCUVSYMLEN Tokens----*/
#define CSL_VLCD_CTL_DCUVSYMLEN_12BITSYM (0x0000u)
#define CSL_VLCD_CTL_DCUVSYMLEN_11BITSYM (0x0001u)

#define CSL_VLCD_CTL_AC0SYMLEN_MASK      (0x0002u)
#define CSL_VLCD_CTL_AC0SYMLEN_SHIFT     (0x0001u)
#define CSL_VLCD_CTL_AC0SYMLEN_RESETVAL  (0x0000u)

/*----AC0SYMLEN Tokens----*/
#define CSL_VLCD_CTL_AC0SYMLEN_12BITSYM  (0x0000u)
#define CSL_VLCD_CTL_AC0SYMLEN_11BITSYM  (0x0001u)

#define CSL_VLCD_CTL_AC1SYMLEN_MASK      (0x0001u)
#define CSL_VLCD_CTL_AC1SYMLEN_SHIFT     (0x0000u)
#define CSL_VLCD_CTL_AC1SYMLEN_RESETVAL  (0x0000u)

/*----AC1SYMLEN Tokens----*/
#define CSL_VLCD_CTL_AC1SYMLEN_12BITSYM  (0x0000u)
#define CSL_VLCD_CTL_AC1SYMLEN_11BITSYM  (0x0001u)

#define CSL_VLCD_CTL_RESETVAL            (0x0000u)

/* VLD_NRBIT_DC */

#define CSL_VLCD_VLD_NRBIT_DC_Y_MASK     (0x1F00u)
#define CSL_VLCD_VLD_NRBIT_DC_Y_SHIFT    (0x0008u)
#define CSL_VLCD_VLD_NRBIT_DC_Y_RESETVAL (0x0000u)

#define CSL_VLCD_VLD_NRBIT_DC_UV_MASK    (0x001Fu)
#define CSL_VLCD_VLD_NRBIT_DC_UV_SHIFT   (0x0000u)
#define CSL_VLCD_VLD_NRBIT_DC_UV_RESETVAL (0x0000u)

#define CSL_VLCD_VLD_NRBIT_DC_RESETVAL   (0x0000u)

/* VLD_NRBIT_AC */

#define CSL_VLCD_VLD_NRBIT_AC_AC0_MASK   (0x1F00u)
#define CSL_VLCD_VLD_NRBIT_AC_AC0_SHIFT  (0x0008u)
#define CSL_VLCD_VLD_NRBIT_AC_AC0_RESETVAL (0x0000u)

#define CSL_VLCD_VLD_NRBIT_AC_AC1_MASK   (0x001Fu)
#define CSL_VLCD_VLD_NRBIT_AC_AC1_SHIFT  (0x0000u)
#define CSL_VLCD_VLD_NRBIT_AC_AC1_RESETVAL (0x0000u)

#define CSL_VLCD_VLD_NRBIT_AC_RESETVAL   (0x0000u)

/* BITS_BPTR */

#define CSL_VLCD_BITS_BPTR_BPTR_MASK     (0x000Fu)
#define CSL_VLCD_BITS_BPTR_BPTR_SHIFT    (0x0000u)
#define CSL_VLCD_BITS_BPTR_BPTR_RESETVAL (0x0000u)

#define CSL_VLCD_BITS_BPTR_RESETVAL      (0x0000u)

/* BITS_WORD */

#define CSL_VLCD_BITS_WORD_BITS_WORD_MASK (0xFFFFu)
#define CSL_VLCD_BITS_WORD_BITS_WORD_SHIFT (0x0000u)
#define CSL_VLCD_BITS_WORD_BITS_WORD_RESETVAL (0x0000u)

#define CSL_VLCD_BITS_WORD_RESETVAL      (0x0000u)

/* BYTE_ALIGN */

#define CSL_VLCD_BYTE_ALIGN_ENABLE_MASK  (0x0002u)
#define CSL_VLCD_BYTE_ALIGN_ENABLE_SHIFT (0x0001u)
#define CSL_VLCD_BYTE_ALIGN_ENABLE_RESETVAL (0x0000u)

#define CSL_VLCD_BYTE_ALIGN_BIT_MASK     (0x0001u)
#define CSL_VLCD_BYTE_ALIGN_BIT_SHIFT    (0x0000u)
#define CSL_VLCD_BYTE_ALIGN_BIT_RESETVAL (0x0000u)

#define CSL_VLCD_BYTE_ALIGN_RESETVAL     (0x0000u)

/* HEAD_ADDR */

#define CSL_VLCD_HEAD_ADDR_HDADDR_MASK   (0x07FFu)
#define CSL_VLCD_HEAD_ADDR_HDADDR_SHIFT  (0x0000u)
#define CSL_VLCD_HEAD_ADDR_HDADDR_RESETVAL (0x0000u)

#define CSL_VLCD_HEAD_ADDR_RESETVAL      (0x0000u)

/* HEAD_NUM */

#define CSL_VLCD_HEAD_NUM_HDNUM_MASK     (0x03FFu)
#define CSL_VLCD_HEAD_NUM_HDNUM_SHIFT    (0x0000u)
#define CSL_VLCD_HEAD_NUM_HDNUM_RESETVAL (0x0000u)

#define CSL_VLCD_HEAD_NUM_RESETVAL       (0x0000u)

/* QIQ_CONFIG0 */

#define CSL_VLCD_QIQ_CONFIG0_SCAN_MASK   (0x3000u)
#define CSL_VLCD_QIQ_CONFIG0_SCAN_SHIFT  (0x000Cu)
#define CSL_VLCD_QIQ_CONFIG0_SCAN_RESETVAL (0x0000u)

/*----SCAN Tokens----*/
#define CSL_VLCD_QIQ_CONFIG0_SCAN_LINEARSCAN (0x0000u)
#define CSL_VLCD_QIQ_CONFIG0_SCAN_ZIGZAGSCAN (0x0001u)
#define CSL_VLCD_QIQ_CONFIG0_SCAN_ALTERNATE_V_SCAN (0x0002u)
#define CSL_VLCD_QIQ_CONFIG0_SCAN_ALTERNATE_H_SCAN (0x0003u)

#define CSL_VLCD_QIQ_CONFIG0_QMATSEL_MASK (0x0700u)
#define CSL_VLCD_QIQ_CONFIG0_QMATSEL_SHIFT (0x0008u)
#define CSL_VLCD_QIQ_CONFIG0_QMATSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG0_IQMATSEL_MASK (0x0070u)
#define CSL_VLCD_QIQ_CONFIG0_IQMATSEL_SHIFT (0x0004u)
#define CSL_VLCD_QIQ_CONFIG0_IQMATSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG0_DCPREDSEL_MASK (0x0007u)
#define CSL_VLCD_QIQ_CONFIG0_DCPREDSEL_SHIFT (0x0000u)
#define CSL_VLCD_QIQ_CONFIG0_DCPREDSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG0_RESETVAL    (0x0000u)

/* QIQ_CONFIG1 */

#define CSL_VLCD_QIQ_CONFIG1_SCAN_MASK   (0x3000u)
#define CSL_VLCD_QIQ_CONFIG1_SCAN_SHIFT  (0x000Cu)
#define CSL_VLCD_QIQ_CONFIG1_SCAN_RESETVAL (0x0000u)

/*----SCAN Tokens----*/
#define CSL_VLCD_QIQ_CONFIG1_SCAN_LINEARSCAN (0x0000u)
#define CSL_VLCD_QIQ_CONFIG1_SCAN_ZIGZAGSCAN (0x0001u)
#define CSL_VLCD_QIQ_CONFIG1_SCAN_ALTERNATE_V_SCAN (0x0002u)
#define CSL_VLCD_QIQ_CONFIG1__RESV_ALTERNATE_H_SCAN (0x0003u)

#define CSL_VLCD_QIQ_CONFIG1_QMATSEL_MASK (0x0700u)
#define CSL_VLCD_QIQ_CONFIG1_QMATSEL_SHIFT (0x0008u)
#define CSL_VLCD_QIQ_CONFIG1_QMATSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG1_IQMATSEL_MASK (0x0070u)
#define CSL_VLCD_QIQ_CONFIG1_IQMATSEL_SHIFT (0x0004u)
#define CSL_VLCD_QIQ_CONFIG1_IQMATSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG1_DCPREDSEL_MASK (0x0007u)
#define CSL_VLCD_QIQ_CONFIG1_DCPREDSEL_SHIFT (0x0000u)
#define CSL_VLCD_QIQ_CONFIG1_DCPREDSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG1_RESETVAL    (0x0000u)

/* QIQ_CONFIG2 */

#define CSL_VLCD_QIQ_CONFIG2_SCAN_MASK   (0x3000u)
#define CSL_VLCD_QIQ_CONFIG2_SCAN_SHIFT  (0x000Cu)
#define CSL_VLCD_QIQ_CONFIG2_SCAN_RESETVAL (0x0000u)

/*----SCAN Tokens----*/
#define CSL_VLCD_QIQ_CONFIG2_SCAN_LINEARSCAN (0x0000u)
#define CSL_VLCD_QIQ_CONFIG2_SCAN_ZIGZAGSCAN (0x0001u)
#define CSL_VLCD_QIQ_CONFIG2_SCAN_ALTERNATE_V_SCAN (0x0002u)
#define CSL_VLCD_QIQ_CONFIG2_SCAN_ALTERNATE_H_SCAN (0x0003u)

#define CSL_VLCD_QIQ_CONFIG2_QMATSEL_MASK (0x0700u)
#define CSL_VLCD_QIQ_CONFIG2_QMATSEL_SHIFT (0x0008u)
#define CSL_VLCD_QIQ_CONFIG2_QMATSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG2_IQMATSEL_MASK (0x0070u)
#define CSL_VLCD_QIQ_CONFIG2_IQMATSEL_SHIFT (0x0004u)
#define CSL_VLCD_QIQ_CONFIG2_IQMATSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG2_DCPREDSEL_MASK (0x0007u)
#define CSL_VLCD_QIQ_CONFIG2_DCPREDSEL_SHIFT (0x0000u)
#define CSL_VLCD_QIQ_CONFIG2_DCPREDSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG2_RESETVAL    (0x0000u)

/* QIQ_CONFIG3 */

#define CSL_VLCD_QIQ_CONFIG3_SCAN_MASK   (0x3000u)
#define CSL_VLCD_QIQ_CONFIG3_SCAN_SHIFT  (0x000Cu)
#define CSL_VLCD_QIQ_CONFIG3_SCAN_RESETVAL (0x0000u)

/*----SCAN Tokens----*/
#define CSL_VLCD_QIQ_CONFIG3_SCAN_LINEARSCAN (0x0000u)
#define CSL_VLCD_QIQ_CONFIG3_SCAN_ZIGZAGSCAN (0x0001u)
#define CSL_VLCD_QIQ_CONFIG3_SCAN_ALTERNATE_V_SCAN (0x0002u)
#define CSL_VLCD_QIQ_CONFIG3_SCAN_ALTERNATE_H_SCAN (0x0003u)

#define CSL_VLCD_QIQ_CONFIG3_QMATSEL_MASK (0x0700u)
#define CSL_VLCD_QIQ_CONFIG3_QMATSEL_SHIFT (0x0008u)
#define CSL_VLCD_QIQ_CONFIG3_QMATSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG3_IQMATSEL_MASK (0x0070u)
#define CSL_VLCD_QIQ_CONFIG3_IQMATSEL_SHIFT (0x0004u)
#define CSL_VLCD_QIQ_CONFIG3_IQMATSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG3_DCPREDSEL_MASK (0x0007u)
#define CSL_VLCD_QIQ_CONFIG3_DCPREDSEL_SHIFT (0x0000u)
#define CSL_VLCD_QIQ_CONFIG3_DCPREDSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG3_RESETVAL    (0x0000u)

/* QIQ_CONFIG4 */

#define CSL_VLCD_QIQ_CONFIG4_SCAN_MASK   (0x3000u)
#define CSL_VLCD_QIQ_CONFIG4_SCAN_SHIFT  (0x000Cu)
#define CSL_VLCD_QIQ_CONFIG4_SCAN_RESETVAL (0x0000u)

/*----SCAN Tokens----*/
#define CSL_VLCD_QIQ_CONFIG4_SCAN_LINEARSCAN (0x0000u)
#define CSL_VLCD_QIQ_CONFIG4_SCAN_ZIGZAGSCAN (0x0001u)
#define CSL_VLCD_QIQ_CONFIG4_SCAN_ALTERNATE_V_SCAN (0x0002u)
#define CSL_VLCD_QIQ_CONFIG4_SCAN_ALTERNATE_H_SCAN (0x0003u)

#define CSL_VLCD_QIQ_CONFIG4_QMATSEL_MASK (0x0700u)
#define CSL_VLCD_QIQ_CONFIG4_QMATSEL_SHIFT (0x0008u)
#define CSL_VLCD_QIQ_CONFIG4_QMATSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG4_IQMATSEL_MASK (0x0070u)
#define CSL_VLCD_QIQ_CONFIG4_IQMATSEL_SHIFT (0x0004u)
#define CSL_VLCD_QIQ_CONFIG4_IQMATSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG4_DCPREDSEL_MASK (0x0007u)
#define CSL_VLCD_QIQ_CONFIG4_DCPREDSEL_SHIFT (0x0000u)
#define CSL_VLCD_QIQ_CONFIG4_DCPREDSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG4_RESETVAL    (0x0000u)

/* QIQ_CONFIG5 */

#define CSL_VLCD_QIQ_CONFIG5_SCAN_MASK   (0x3000u)
#define CSL_VLCD_QIQ_CONFIG5_SCAN_SHIFT  (0x000Cu)
#define CSL_VLCD_QIQ_CONFIG5_SCAN_RESETVAL (0x0000u)

/*----SCAN Tokens----*/
#define CSL_VLCD_QIQ_CONFIG5_SCAN_LINEARSCAN (0x0000u)
#define CSL_VLCD_QIQ_CONFIG5_SCAN_ZIGZAGSCAN (0x0001u)
#define CSL_VLCD_QIQ_CONFIG5_SCAN_ALTERNATE_V_SCAN (0x0002u)
#define CSL_VLCD_QIQ_CONFIG5_SCAN_ALTERNATE_H_SCAN (0x0003u)

#define CSL_VLCD_QIQ_CONFIG5_QMATSEL_MASK (0x0700u)
#define CSL_VLCD_QIQ_CONFIG5_QMATSEL_SHIFT (0x0008u)
#define CSL_VLCD_QIQ_CONFIG5_QMATSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG5_IQMATSEL_MASK (0x0070u)
#define CSL_VLCD_QIQ_CONFIG5_IQMATSEL_SHIFT (0x0004u)
#define CSL_VLCD_QIQ_CONFIG5_IQMATSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG5_DCPREDSEL_MASK (0x0007u)
#define CSL_VLCD_QIQ_CONFIG5_DCPREDSEL_SHIFT (0x0000u)
#define CSL_VLCD_QIQ_CONFIG5_DCPREDSEL_RESETVAL (0x0000u)

#define CSL_VLCD_QIQ_CONFIG5_RESETVAL    (0x0000u)

/* VLD_ERRCTL */

#define CSL_VLCD_VLD_ERRCTL_EOB_MASK     (0x0004u)
#define CSL_VLCD_VLD_ERRCTL_EOB_SHIFT    (0x0002u)
#define CSL_VLCD_VLD_ERRCTL_EOB_RESETVAL (0x0001u)

/*----EOB Tokens----*/
#define CSL_VLCD_VLD_ERRCTL_EOB_OFF      (0x0000u)
#define CSL_VLCD_VLD_ERRCTL_EOB_ON       (0x0001u)

#define CSL_VLCD_VLD_ERRCTL_UVLD_MASK    (0x0001u)
#define CSL_VLCD_VLD_ERRCTL_UVLD_SHIFT   (0x0000u)
#define CSL_VLCD_VLD_ERRCTL_UVLD_RESETVAL (0x0000u)

/*----UVLD Tokens----*/
#define CSL_VLCD_VLD_ERRCTL_UVLD_OFF     (0x0000u)
#define CSL_VLCD_VLD_ERRCTL_UVLD_ON      (0x0001u)

#define CSL_VLCD_VLD_ERRCTL_RESETVAL     (0x0004u)

/* VLD_ERRSTAT */

#define CSL_VLCD_VLD_ERRSTAT_RINGBUFF_MASK (0x0008u)
#define CSL_VLCD_VLD_ERRSTAT_RINGBUFF_SHIFT (0x0003u)
#define CSL_VLCD_VLD_ERRSTAT_RINGBUFF_RESETVAL (0x0000u)

#define CSL_VLCD_VLD_ERRSTAT_EOB_MASK    (0x0004u)
#define CSL_VLCD_VLD_ERRSTAT_EOB_SHIFT   (0x0002u)
#define CSL_VLCD_VLD_ERRSTAT_EOB_RESETVAL (0x0000u)

/*----EOB Tokens----*/
#define CSL_VLCD_VLD_ERRSTAT_EOB_NOERROR (0x0000u)
#define CSL_VLCD_VLD_ERRSTAT_EOB_NO_EOB_IN_VLD (0x0001u)

#define CSL_VLCD_VLD_ERRSTAT_VLD_MASK    (0x0002u)
#define CSL_VLCD_VLD_ERRSTAT_VLD_SHIFT   (0x0001u)
#define CSL_VLCD_VLD_ERRSTAT_VLD_RESETVAL (0x0000u)

/*----VLD Tokens----*/
#define CSL_VLCD_VLD_ERRSTAT_VLD_NOERROR (0x0000u)
#define CSL_VLCD_VLD_ERRSTAT_VLD_NON_FF00_IN_MB (0x0001u)

#define CSL_VLCD_VLD_ERRSTAT_UVLD_MASK   (0x0001u)
#define CSL_VLCD_VLD_ERRSTAT_UVLD_SHIFT  (0x0000u)
#define CSL_VLCD_VLD_ERRSTAT_UVLD_RESETVAL (0x0000u)

/*----UVLD Tokens----*/
#define CSL_VLCD_VLD_ERRSTAT_UVLD_NOERROR (0x0000u)
#define CSL_VLCD_VLD_ERRSTAT_UVLD_OUT_OF_TABLE_ENTRY_IN_MB (0x0001u)

#define CSL_VLCD_VLD_ERRSTAT_RESETVAL    (0x0000u)

/* RING_START */

#define CSL_VLCD_RING_START_RSTART_MASK  (0x1FFFu)
#define CSL_VLCD_RING_START_RSTART_SHIFT (0x0000u)
#define CSL_VLCD_RING_START_RSTART_RESETVAL (0x0000u)

#define CSL_VLCD_RING_START_RESETVAL     (0x0000u)

/* RING_END */

#define CSL_VLCD_RING_END_REND_MASK      (0x1FFFu)
#define CSL_VLCD_RING_END_REND_SHIFT     (0x0000u)
#define CSL_VLCD_RING_END_REND_RESETVAL  (0x1FFFu)

#define CSL_VLCD_RING_END_RESETVAL       (0x1FFFu)

/* CLKCTRL */

#define CSL_VLCD_CLKCTRL_ENDIAN_MASK     (0x0080u)
#define CSL_VLCD_CLKCTRL_ENDIAN_SHIFT    (0x0007u)
#define CSL_VLCD_CLKCTRL_ENDIAN_RESETVAL (0x0001u)

/*----ENDIAN Tokens----*/
#define CSL_VLCD_CLKCTRL_ENDIAN_LITTLE   (0x0001u)

#define CSL_VLCD_CLKCTRL_VLD_SEL_MASK    (0x0040u)
#define CSL_VLCD_CLKCTRL_VLD_SEL_SHIFT   (0x0006u)
#define CSL_VLCD_CLKCTRL_VLD_SEL_RESETVAL (0x0000u)

/*----VLD_SEL Tokens----*/
#define CSL_VLCD_CLKCTRL_VLD_SEL_DM270   (0x0000u)
#define CSL_VLCD_CLKCTRL_VLD_SEL_MPEG4_RVLC (0x0001u)

#define CSL_VLCD_CLKCTRL_MPEG_MODE2_MASK (0x0030u)
#define CSL_VLCD_CLKCTRL_MPEG_MODE2_SHIFT (0x0004u)
#define CSL_VLCD_CLKCTRL_MPEG_MODE2_RESETVAL (0x0000u)

/*----MPEG_MODE2 Tokens----*/
#define CSL_VLCD_CLKCTRL_MPEG_MODE2_MPEG4 (0x0000u)
#define CSL_VLCD_CLKCTRL_MPEG_MODE2_MPEG4DATAPARTITION (0x0001u)
#define CSL_VLCD_CLKCTRL_MPEG_MODE2_MPEG4RVLC_D (0x0002u)
#define CSL_VLCD_CLKCTRL_MPEG_MODE2_WMV9 (0x0003u)

#define CSL_VLCD_CLKCTRL_SCAN_MODE_MASK  (0x0008u)
#define CSL_VLCD_CLKCTRL_SCAN_MODE_SHIFT (0x0003u)
#define CSL_VLCD_CLKCTRL_SCAN_MODE_RESETVAL (0x0000u)

/*----SCAN_MODE Tokens----*/
#define CSL_VLCD_CLKCTRL_SCAN_MODE_SEL_BY_MODE (0x0000u)
#define CSL_VLCD_CLKCTRL_SCAN_MODE_SEL_BY_QIQCFG (0x0001u)

#define CSL_VLCD_CLKCTRL_MPEG2_MASK      (0x0004u)
#define CSL_VLCD_CLKCTRL_MPEG2_SHIFT     (0x0002u)
#define CSL_VLCD_CLKCTRL_MPEG2_RESETVAL  (0x0000u)

/*----MPEG2 Tokens----*/
#define CSL_VLCD_CLKCTRL_MPEG2_MPEG1     (0x0000u)
#define CSL_VLCD_CLKCTRL_MPEG2_MPEG2     (0x0001u)

#define CSL_VLCD_CLKCTRL_ESCCODE_MASK    (0x0002u)
#define CSL_VLCD_CLKCTRL_ESCCODE_SHIFT   (0x0001u)
#define CSL_VLCD_CLKCTRL_ESCCODE_RESETVAL (0x0000u)

/*----ESCCODE Tokens----*/
#define CSL_VLCD_CLKCTRL_ESCCODE_ESC3    (0x0000u)
#define CSL_VLCD_CLKCTRL_ESCCODE_ESC1_2_AND_3 (0x0001u)

#define CSL_VLCD_CLKCTRL_CLKON_MASK      (0x0001u)
#define CSL_VLCD_CLKCTRL_CLKON_SHIFT     (0x0000u)
#define CSL_VLCD_CLKCTRL_CLKON_RESETVAL  (0x0000u)

/*----CLKON Tokens----*/
#define CSL_VLCD_CLKCTRL_CLKON_ON        (0x0000u)
#define CSL_VLCD_CLKCTRL_CLKON_OFF       (0x0001u)

#define CSL_VLCD_CLKCTRL_RESETVAL        (0x0080u)

/* VLD_PREFIX_DC */

#define CSL_VLCD_VLD_PREFIX_DC_NBITS_DC_Y_MASK (0x1F00u)
#define CSL_VLCD_VLD_PREFIX_DC_NBITS_DC_Y_SHIFT (0x0008u)
#define CSL_VLCD_VLD_PREFIX_DC_NBITS_DC_Y_RESETVAL (0x0000u)

#define CSL_VLCD_VLD_PREFIX_DC_NBITS_DC_UV_MASK (0x001Fu)
#define CSL_VLCD_VLD_PREFIX_DC_NBITS_DC_UV_SHIFT (0x0000u)
#define CSL_VLCD_VLD_PREFIX_DC_NBITS_DC_UV_RESETVAL (0x0000u)

#define CSL_VLCD_VLD_PREFIX_DC_RESETVAL  (0x0000u)

/* VLD_PREFIX_AC */

#define CSL_VLCD_VLD_PREFIX_AC_NBITS_AC0_MASK (0x1F00u)
#define CSL_VLCD_VLD_PREFIX_AC_NBITS_AC0_SHIFT (0x0008u)
#define CSL_VLCD_VLD_PREFIX_AC_NBITS_AC0_RESETVAL (0x0000u)

#define CSL_VLCD_VLD_PREFIX_AC_NBITS_AC1_MASK (0x001Fu)
#define CSL_VLCD_VLD_PREFIX_AC_NBITS_AC1_SHIFT (0x0000u)
#define CSL_VLCD_VLD_PREFIX_AC_NBITS_AC1_RESETVAL (0x0000u)

#define CSL_VLCD_VLD_PREFIX_AC_RESETVAL  (0x0000u)

/* WMV9_CFG */

#define CSL_VLCD_WMV9_CFG_SYMINBLK_MASK  (0x0300u)
#define CSL_VLCD_WMV9_CFG_SYMINBLK_SHIFT (0x0008u)
#define CSL_VLCD_WMV9_CFG_SYMINBLK_RESETVAL (0x0000u)

/*----SYMINBLK Tokens----*/
#define CSL_VLCD_WMV9_CFG_SYMINBLK_64    (0x0000u)
#define CSL_VLCD_WMV9_CFG_SYMINBLK_32    (0x0001u)
#define CSL_VLCD_WMV9_CFG_SYMINBLK_16    (0x0002u)

#define CSL_VLCD_WMV9_CFG_SCANTBL_MASK   (0x0080u)
#define CSL_VLCD_WMV9_CFG_SCANTBL_SHIFT  (0x0007u)
#define CSL_VLCD_WMV9_CFG_SCANTBL_RESETVAL (0x0000u)

#define CSL_VLCD_WMV9_CFG_PQUANT_MASK    (0x0040u)
#define CSL_VLCD_WMV9_CFG_PQUANT_SHIFT   (0x0006u)
#define CSL_VLCD_WMV9_CFG_PQUANT_RESETVAL (0x0000u)

#define CSL_VLCD_WMV9_CFG_QSCALE_MASK    (0x0030u)
#define CSL_VLCD_WMV9_CFG_QSCALE_SHIFT   (0x0004u)
#define CSL_VLCD_WMV9_CFG_QSCALE_RESETVAL (0x0000u)

#define CSL_VLCD_WMV9_CFG_INTRA_RATE_MASK (0x000Cu)
#define CSL_VLCD_WMV9_CFG_INTRA_RATE_SHIFT (0x0002u)
#define CSL_VLCD_WMV9_CFG_INTRA_RATE_RESETVAL (0x0000u)

/*----INTRA_RATE Tokens----*/
#define CSL_VLCD_WMV9_CFG_INTRA_RATE_LOW_MO (0x0000u)
#define CSL_VLCD_WMV9_CFG_INTRA_RATE_HI_MO (0x0001u)
#define CSL_VLCD_WMV9_CFG_INTRA_RATE_MID_RATE (0x0002u)
#define CSL_VLCD_WMV9_CFG_INTRA_RATE_HI_RATE (0x0003u)

#define CSL_VLCD_WMV9_CFG_INTER_RATE_MASK (0x0003u)
#define CSL_VLCD_WMV9_CFG_INTER_RATE_SHIFT (0x0000u)
#define CSL_VLCD_WMV9_CFG_INTER_RATE_RESETVAL (0x0000u)

/*----INTER_RATE Tokens----*/
#define CSL_VLCD_WMV9_CFG_INTER_RATE_LOW_MO (0x0000u)
#define CSL_VLCD_WMV9_CFG_INTER_RATE_HI_MO (0x0001u)
#define CSL_VLCD_WMV9_CFG_INTER_RATE_MID_RATE (0x0002u)
#define CSL_VLCD_WMV9_CFG_INTER_RATE_HI_RATE (0x0003u)

#define CSL_VLCD_WMV9_CFG_RESETVAL       (0x0000u)

/* FIRST_FRAME */

#define CSL_VLCD_FIRST_FRAME_FF_MASK     (0x0001u)
#define CSL_VLCD_FIRST_FRAME_FF_SHIFT    (0x0000u)
#define CSL_VLCD_FIRST_FRAME_FF_RESETVAL (0x0000u)

#define CSL_VLCD_FIRST_FRAME_RESETVAL    (0x0000u)

/* H264_MODE */

#define CSL_VLCD_H264_MODE_IQMODE_MASK   (0x0004u)
#define CSL_VLCD_H264_MODE_IQMODE_SHIFT  (0x0002u)
#define CSL_VLCD_H264_MODE_IQMODE_RESETVAL (0x0000u)

/*----IQMODE Tokens----*/
#define CSL_VLCD_H264_MODE_IQMODE_CHROMA (0x0000u)
#define CSL_VLCD_H264_MODE_IQMODE_LUMA   (0x0001u)

#define CSL_VLCD_H264_MODE_H264_SCAN_MASK (0x0002u)
#define CSL_VLCD_H264_MODE_H264_SCAN_SHIFT (0x0001u)
#define CSL_VLCD_H264_MODE_H264_SCAN_RESETVAL (0x0000u)

/*----H264_SCAN Tokens----*/
#define CSL_VLCD_H264_MODE_H264_SCAN_OFF (0x0000u)
#define CSL_VLCD_H264_MODE_H264_SCAN_ON  (0x0001u)

#define CSL_VLCD_H264_MODE_H264_CAVLD_MASK (0x0001u)
#define CSL_VLCD_H264_MODE_H264_CAVLD_SHIFT (0x0000u)
#define CSL_VLCD_H264_MODE_H264_CAVLD_RESETVAL (0x0000u)

/*----H264_CAVLD Tokens----*/
#define CSL_VLCD_H264_MODE_H264_CAVLD_OFF (0x0000u)
#define CSL_VLCD_H264_MODE_H264_CAVLD_ON (0x0001u)

#define CSL_VLCD_H264_MODE_RESETVAL      (0x0000u)

/* NRBITS_THRED */

#define CSL_VLCD_NRBITS_THRED_THRESHOLD_MASK (0x000Fu)
#define CSL_VLCD_NRBITS_THRED_THRESHOLD_SHIFT (0x0000u)
#define CSL_VLCD_NRBITS_THRED_THRESHOLD_RESETVAL (0x0006u)

#define CSL_VLCD_NRBITS_THRED_RESETVAL   (0x0006u)

#endif
/* Rev.No.   Date/Time               ECN No.          Modifier      */
/* -------   ---------               -------          --------      */

/* 1         21 Oct 2004 10:09:18    3560             xkeshavm      */
/*                                                                  */
/* Added vpss source and header files                               */
/********************************************************************/ 
/* Rev.No.   Date/Time               ECN No.          Modifier      */
/* -------   ---------               -------          --------      */

/* 1         13 Nov 2005 12:48:00    401              x0029935      */
/*                                                                  */
/* Modified from davicni CSL files to Dm350                         */
/* First CSL files build up fro Dm350                               */
/********************************************************************/ 
